<?php

namespace AppBundle\Repository;

/**
 * Rememberme_tokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rememberme_tokenRepository extends \Doctrine\ORM\EntityRepository
{
}
