<?php

namespace AppBundle\Repository;

/**
 * TokenStorage_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenStorage_UserRepository extends \Doctrine\ORM\EntityRepository
{
}
