<?php

namespace AppBundle\Repository;

/**
 * TokenStorageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenStorageRepository extends \Doctrine\ORM\EntityRepository
{
}
