app:
    resource: '@AppBundle/Controller/'
    type: annotation
lucky:
    path:    /lucky
    defaults: { _controller: AppBundle:LuckyController}
admin:
    path:    /admin
    defaults: { _controller: AppBundle:DefaultController}