# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        database_users:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            json_login:
                check_path: login_token
            # activate different ways to authenticate
            logout_on_user_change: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: admin
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                name: REMEMBERME
                secret: "%secret%"
                lifetime: 31536000
            logout:
                path: security_logout
            provider: database_users


    access_control:
        - { path: '^/admin', roles: ROLE_ADMIN }
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
