AppBundle\Entity\TokenStorage_User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TokenStorage_UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: string
            length: 255
        tokenStorageId:
            type: string
            length: 255
    lifecycleCallbacks: {  }
